### ISSUE TITLE
Reaching out!

### ISSUE THREAD

**Issue by jweig0ld** [yamule/rust_pdbloader#1]
Hey Yamabuki, my name's Jamie. I'm reaching out because I've seen you've been forking a lot in your free time with today's (mostly diffusion-based) biology models! I'd love to talk to you about your experience using them and what you're doing with them.

I've tried looking for another way to contact you, but I can't find any. Could you send me an email address or a LinkedIn or Discord profile or somewhere else I can reach you? :-)

**Comment by yamule** [comment]
I'm super-busy now and I may not be able to respond if you offer me something.
Sorry for the inconvenience.
